install.packages("psych")
library(psych)
?psych
data("iris")
View(iris)
species_dummy <- dummy.code(iris$Species, group = NULL)
?dummy.code()
iris <- as.data.frame(cbind(iris,species_dummy))
View(iris)
age <- c(1,2,NA,4)
age.i <- impute(age)
# Could have used impute(age,2.5), impute(age,mean), impute(age,"random")
View(age.i)
summary(age.i)